/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compuertas;

/**
 *
 * @author ellioth
 */
public class ConecComp extends javax.swing.JFrame {

    /**
     * Creates new form valores
     */
    public ConecComp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnsElc = new javax.swing.ButtonGroup();
        BtnsTo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conexion de compuertas\n\n");
        setMinimumSize(new java.awt.Dimension(436, 315));
        getContentPane().setLayout(null);

        jLabel1.setText("Puertos de compuerta electa");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 190, 178, 16);

        jLabel2.setText("Entradas a compuerta");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 190, 136, 16);

        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(21, 50, 384, 132);

        jLabel3.setFont(new java.awt.Font("Kokonor", 0, 16)); // NOI18N
        jLabel3.setText("Conexion con compuertas");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 10, 190, 29);

        BtnsTo.add(jRadioButton1);
        jRadioButton1.setText("Entrada 1");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(270, 230, 91, 23);

        BtnsTo.add(jRadioButton2);
        jRadioButton2.setText("Entrada 2");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(270, 270, 91, 23);

        BtnsElc.add(jRadioButton3);
        jRadioButton3.setText("Entrada 2");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(30, 250, 91, 23);

        BtnsElc.add(jRadioButton4);
        jRadioButton4.setText("Salida");
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(30, 280, 69, 23);

        BtnsElc.add(jRadioButton5);
        jRadioButton5.setText("Entrada 1");
        getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(30, 220, 91, 23);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 10, 75, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConecComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConecComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConecComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConecComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConecComp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BtnsElc;
    private javax.swing.ButtonGroup BtnsTo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
