/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compuertas;

import javax.swing.DefaultListModel;


/**
 *
 * @author ellioth
 */
public class cuadroVal extends javax.swing.JFrame {
    private int compuerta;
    private String Sel;
    /**
     * Creates new form cuadroVal
     */
    public cuadroVal() {
        compuerta=0;
        Sel="";
        initComponents();
    }

    public void setTotalL(String args){
        lista.addElement(args);
    }
    
    public String getCompuerta(){
        return Sel;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista= new DefaultListModel();
        ListaCompuertas = new javax.swing.JList();
        out = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        CompSel = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(367, 252));
        getContentPane().setLayout(null);

        ListaCompuertas.setModel(lista);
        jScrollPane1.setViewportView(ListaCompuertas);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 40, 300, 132);

        out.setText("Salir");
        out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outActionPerformed(evt);
            }
        });
        getContentPane().add(out);
        out.setBounds(240, 190, 75, 29);

        jLabel2.setFont(new java.awt.Font("Kokonor", 0, 18)); // NOI18N
        jLabel2.setText("Seleccionar compuerta");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 10, 190, 31);

        CompSel.setText("Seleccionar");
        CompSel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompSelActionPerformed(evt);
            }
        });
        getContentPane().add(CompSel);
        CompSel.setBounds(50, 190, 97, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String getSel(){
        return Sel;
    }
    
    
    
    private void outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_outActionPerformed

    private void CompSelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompSelActionPerformed
        // TODO add your handling code here:
        compuerta=ListaCompuertas.getAnchorSelectionIndex();
        Sel= (String)lista.get(compuerta);
    }//GEN-LAST:event_CompSelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cuadroVal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cuadroVal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cuadroVal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cuadroVal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cuadroVal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CompSel;
    private javax.swing.JList ListaCompuertas;
    private DefaultListModel lista;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton out;
    // End of variables declaration//GEN-END:variables
}
